repos:
  - hooks:
      - id: black
        language_version: python3
    repo: https://github.com/ambv/black
    rev: 22.6.0
  - hooks:
      - id: isort
        language_version: python3
    repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
  - hooks:
      - id: flake8
        language_version: python3
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-debugger
          - flake8-string-format
    repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
  - repo: local
    hooks:
    - id: mypy
      name: mypy
      entry: mypy
      files: ^aiooss/
      language: system
      types: [python]
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
  - hooks:
      - args:
          - -i
          - "2"
        id: beautysh
        language_version: python3
    repo: https://github.com/lovesegfault/beautysh
    rev: 6.0.1

