name: aiooss test

on:
  pull_request:
    branches:
      - main 
  push:
    branches:
      - main

jobs:
  pre-commit-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install ".[dev]"
    - uses: pre-commit/action@v3.0.0

  tests:
    name: ${{ matrix.os }} Python-${{ matrix.pyv}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        pyv: ["3.7", "3.8", "3.9", "3.10"]
        os: [ubuntu-20.04, windows-latest, macos-latest]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.pyv }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.pyv }}

      - name: install dependencies
        run: |
          python -m pip install ".[dev]" pip
          pip --version
          nox --version

      - name: Lint code and check dependencies
        run: nox -s lint safety

      - name: Run Tests
        env:
          OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID}}
          OSS_SECRET_ACCESS_KEY: ${{ secrets.OSS_SECRET_ACCESS_KEY}}
          OSS_ENDPOINT: ${{ secrets.OSS_ENDPOINT}}
          OSS_TEST_BUCKET_NAME: ${{ secrets.OSS_TEST_BUCKET_NAME}}
        shell: bash -l {0}
        run: nox -s tests-${{ matrix.pyv }}

      - name: Upload coverage report
        uses: codecov/codecov-action@v3.1.0

      - name: Build package
        run: nox -s build
